parameters:
#    egrajeda_recline_js.example.class: Egrajeda\ReclineJsBundle\Example

services:
#    egrajeda_recline_js.example:
#        class: %egrajeda_recline_js.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
